---
title: "Portfolio_Part_1"
author: "Ronit Kumar"
format: html
editor: visual
---

# Data Description
### Data source 

My data is a subset from the U.S Airline delay dataset from Kaggle released in 2008. It had near about 2 million rows, i created my own working subset by randomly sampling around 400000 rows using python.

### Data Description
In this data, each row is one individual flight. It has information such as when the flight was scheduled, when it departed or arrived, the airports involved and different causes of the delay.

Some key variables in my project are:
DepTime - Actual Departure time (HHMM Format)
ArrDelay - Arrival delay (Numeric)
Origin - Origin Airport Code (String)
Dest - Destination Airport Code (String)
CarrierDelay - Delay caused by airline carrier (Numeric)
WeatherDelay - Delay caused by weather ( Numeric)
SecurityDelay - Delay Caused by Security  (NUmeric)
LAteAirCraftDelay - Delay caused by late incoming aircraft (Numeric)
NASDelay-  Delay caused by National Aviation System. (Numeric)

# Research Questions
### My main research questions are
1. When do flight delays peak during the day?

2. Which causes of delay contribute thre most total delay time?

3. Which flight routes have the worst average delays?

These questions tells us when delays happen and why they happen while also giving us information regarding which routes are affected the most.


# Data Visualization

What do you want your final visualization to look like?

Initially i opted for just bar graphs for all three questions, but after brief discussions with the professor i might have to select different visualizations for each question. I am currently in the process of choosing what visualization select from. Right now i am in the process of doing heatmap for question 3.

What do you want to highlight on your final visualizations in order to answer your research questions? How do you plan to do that?

I want the first question to be self explanatory, by using a simple bar graph the audience can easily see where flight delays occur. I plan on ordering it either by desc or ascending and plan on making use of gestalt principals for this. I am deciding what visualization to use for my second question but for the third question using a heat map seems like a good option as i can use different color intensities to show which routes have a higher average arrival delay.

What is missing from your data or would need to change in your data to create these visualizations ?

I need to convert HHMM format of time variables to hour based to make it usable for my graphs. There are also some columns that have missing values which i will deal with in the section below.

